"""add user payment handles

Revision ID: ef1db306cf00
Revises: 717f01ee8439
Create Date: 2026-09-22 21:50:16.596351
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ef1db306cf00'
down_revision: Union[str, None] = '717f01ee8439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('venmo_handle', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('paypal_handle', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('cashapp_cashtag', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cashapp_cashtag')
    op.drop_column('users', 'paypal_handle')
    op.drop_column('users', 'venmo_handle')
    # ### end Alembic commands ###
